var iTunesStoreCountries = [ 
  { name: 'Albania',
    code: 'AL',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Algeria',
    code: 'DZ',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Angola',
    code: 'AO',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Anguilla',
    code: 'AI',
    features: 
     [ 'podcasts',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Antigua & Barbuda',
    code: 'AG',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Argentina',
    code: 'AR',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Armenia',
    code: 'AM',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Australia',
    code: 'AU',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'textbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'tvshows',
       'hdtvshows',
       'seasonpasses',
       'shortfilms' ] },
  { name: 'Austria',
    code: 'AT',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Azerbaijan',
    code: 'AZ',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Bahamas',
    code: 'BS',
    features: 
     [ 'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Bahrain',
    code: 'BH',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Barbados',
    code: 'BB',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Belarus',
    code: 'BY',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'movierentals' ] },
  { name: 'Belgium',
    code: 'BE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Belize',
    code: 'BZ',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Benin',
    code: 'BJ',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Bermuda',
    code: 'BM',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Bhutan',
    code: 'BT',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Bolivia',
    code: 'BO',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Botswana',
    code: 'BW',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Brazil',
    code: 'BR',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'British Virgin Islands',
    code: 'VG',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Brunei',
    code: 'BN',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Bulgaria',
    code: 'BG',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Burkina-Faso',
    code: 'BF',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Cambodia',
    code: 'KH',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Canada',
    code: 'CA',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'textbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'tvshows',
       'hdtvshows',
       'seasonpasses',
       'shortfilms' ] },
  { name: 'Cape Verde',
    code: 'CV',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Cayman Islands',
    code: 'KY',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Chad',
    code: 'TD',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Chile',
    code: 'CL',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'China',
    code: 'CN',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Colombia',
    code: 'CO',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Congo, Republic of',
    code: 'CG',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Costa Rica',
    code: 'CR',
    features: 
     [ 'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Croatia',
    code: 'HR',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Cyprus',
    code: 'CY',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Czech Republic',
    code: 'CZ',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Denmark',
    code: 'DK',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Dominica',
    code: 'DM',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Dominican Republic',
    code: 'DO',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Ecuador',
    code: 'EC',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Egypt',
    code: 'EG',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'movierentals' ] },
  { name: 'El Salvador',
    code: 'SV',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Estonia',
    code: 'EE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Fiji',
    code: 'FJ',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Finland',
    code: 'FI',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'France',
    code: 'FR',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'tvshows',
       'hdtvshows',
       'seasonpasses',
       'shortfilms' ] },
  { name: 'Gambia',
    code: 'GM',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Germany',
    code: 'DE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'tvshows',
       'hdtvshows',
       'seasonpasses',
       'shortfilms' ] },
  { name: 'Ghana',
    code: 'GH',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'movies',
       'movierentals' ] },
  { name: 'Greece',
    code: 'GR',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Grenada',
    code: 'GD',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Guatemala',
    code: 'GT',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Guinea Bissau',
    code: 'GW',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Guyana',
    code: 'GY',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Honduras',
    code: 'HN',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Hong Kong',
    code: 'HK',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Hungary',
    code: 'HU',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Iceland',
    code: 'IS',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'India',
    code: 'IN',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Indonesia',
    code: 'ID',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'movierentals' ] },
  { name: 'Ireland',
    code: 'IE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'digitalcopies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Israel',
    code: 'IL',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Italy',
    code: 'IT',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Jamaica',
    code: 'JM',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Japan',
    code: 'JP',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Jordan',
    code: 'JO',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'movierentals' ] },
  { name: 'Kazakhstan',
    code: 'KZ',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Kenya',
    code: 'KE',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Kuwait',
    code: 'KW',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Krygyzstan',
    code: 'KG',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Laos',
    code: 'LA',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Latvia',
    code: 'LV',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Lebanon',
    code: 'LB',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'movierentals' ] },
  { name: 'Liberia',
    code: 'LR',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Lithuania',
    code: 'LT',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Luxembourg',
    code: 'LU',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Macau',
    code: 'MO',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Macedonia',
    code: 'MK',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Madagascar',
    code: 'MG',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Malawi',
    code: 'MW',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Malaysia',
    code: 'MY',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Mali',
    code: 'ML',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Malta, Republic of',
    code: 'MT',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Mauritania',
    code: 'MR',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Mauritius',
    code: 'MU',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Mexico',
    code: 'MX',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Micronesian, Federated States of',
    code: 'FM',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Mongolia',
    code: 'MN',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Montserrat',
    code: 'MS',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Moldova',
    code: 'MD',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Mozambique',
    code: 'MZ',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Namibia',
    code: 'NA',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Nepal',
    code: 'NP',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Netherlands',
    code: 'NL',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'New Zealand',
    code: 'NZ',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'audiobooks',
       'movies',
       'digitalcopies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Nicaragua',
    code: 'NI',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Niger',
    code: 'NE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Nigeria',
    code: 'NG',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Norway',
    code: 'NO',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Oman',
    code: 'OM',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'movierentals' ] },
  { name: 'Pakistan',
    code: 'PK',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Palau',
    code: 'PW',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Panama',
    code: 'PA',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Papua New Guinea',
    code: 'PG',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Paraguay',
    code: 'PY',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Peru',
    code: 'PE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Philippines',
    code: 'PH',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Poland',
    code: 'PL',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Portugal',
    code: 'PT',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Qatar',
    code: 'QA',
    features: 
     [ 'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Romania',
    code: 'RO',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps' ] },
  { name: 'Russia',
    code: 'RU',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'movierentals',
       'shortfilms' ] },
  { name: 'St. Kitts & Nevis',
    code: 'KN',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'St. Lucia',
    code: 'LC',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'St. Vincent & The Grenadines',
    code: 'VC',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Sao Tome e Principe',
    code: 'ST',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Saudi Arabia',
    code: 'SA',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'movierentals' ] },
  { name: 'Senegal',
    code: 'SN',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Seychelles',
    code: 'SC',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Sierra Leone',
    code: 'SL',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Singapore',
    code: 'SG',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Slovakia',
    code: 'SK',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Slovenia',
    code: 'SI',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Soloman Islands',
    code: 'SB',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'South Africa',
    code: 'ZA',
    features: 
     [ 'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'South Korea',
    code: 'KR',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Spain',
    code: 'ES',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Sri Lanka',
    code: 'LK',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Suriname',
    code: 'SR',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Swaziland',
    code: 'SZ',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Sweden',
    code: 'SE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Switzerland',
    code: 'CH',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'songs',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Taiwan',
    code: 'TW',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Tajikistan',
    code: 'TJ',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Tanzania',
    code: 'TZ',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Thailand',
    code: 'TH',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Trinidad & Tobago',
    code: 'TT',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Tunisia',
    code: 'TN',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Turkey',
    code: 'TR',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'movierentals',
       'shortfilms' ] },
  { name: 'Turkmenistan',
    code: 'TM',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Turks & Caicos',
    code: 'TC',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Uganda',
    code: 'UG',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Ukraine',
    code: 'UA',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'United Arab Emirates',
    code: 'AE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'movierentals',
       'shortfilms' ] },
  { name: 'United Kingdom',
    code: 'GB',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'textbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'tvshows',
       'hdtvshows',
       'seasonpasses',
       'shortfilms' ] },
  { name: 'United States',
    code: 'US',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'paidbooks',
       'textbooks',
       'songs',
       'itunespasses',
       'ituneslps',
       'audiobooks',
       'movies',
       'itunesextras',
       'digitalcopies',
       'movierentals',
       'tvshows',
       'hdtvshows',
       'seasonpasses',
       'shortfilms' ] },
  { name: 'Uruguay',
    code: 'UY',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Uzbekistan',
    code: 'UZ',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks', 'songs', 'ituneslps' ] },
  { name: 'Venezuela',
    code: 'VE',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'movies',
       'itunesextras',
       'movierentals',
       'shortfilms' ] },
  { name: 'Vietnam',
    code: 'VN',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] },
  { name: 'Yemen',
    code: 'YE',
    features: [ 'apps', 'podcasts', 'itunesu', 'freebooks' ] },
  { name: 'Zimbabwe',
    code: 'ZW',
    features: 
     [ 'apps',
       'podcasts',
       'itunesu',
       'freebooks',
       'songs',
       'ituneslps',
       'movies',
       'itunesextras',
       'movierentals' ] } ];